apiVersion: apps/v1
kind: Deployment
metadata:
  name: spammer-app
  labels:
    app: spammer-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spammer-app
  template:
    metadata:
      labels:
        app: spammer-app
    spec:
      containers:
        - name: spammer-app
          image: anastasiiabezruka/spammer-nodejs-app:latest
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 15
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service-name: spammer-app-service
              servicePort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spammer-app-service
spec:
  ports:
    - port: 8080
  selector:
    app: spammer-app